name: {{projectName.snakeCase()}}
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  app_tracking_transparency: ^2.0.4
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2
  device_info_plus: ^9.1.2
  encrypt: ^5.0.3
  firebase_analytics: ^10.8.10
  firebase_app_installations: ^0.2.4+18
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_messaging: ^14.7.20
  firebase_remote_config: ^4.3.18
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.7
  get_storage: ^2.1.1
  http_certificate_pinning: ^2.1.3
  image_picker: ^1.0.7
  injectable: ^2.4.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  network_info_plus: ^4.0.1
  open_filex: ^4.4.0
  package_info_plus: ^5.1.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  route_map: ^0.0.17
  webview_flutter: ^4.2.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  injectable_generator: ^2.6.0
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0
  route_map_generator: ^0.0.17
  url_launcher: ^6.2.5

flutter_native_splash:
  #image: assets/image/logo.png
  color: "#ec6e01"
  #color_dark: "#303030"

flutter_icons:
  # android: "launcher_icon"
  ios: true
  image_path: assets/images/app_icon.png
  remove_alpha_ios: true
  # adaptive_icon_background: assets/images/background.png

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
